
# coding: utf-8

# In[ ]:

# The purpose of this program is to give you an example of how to access the data generated by the saddle point finder.
# Once you know how to access and understand the data then you can convert it to whatever format you'd like i.e. matlab


# In[ ]:

import numpy as np


# In[ ]:

# Select the name of the directory that contains the data that you would like to load
# The program only looks for subdirectories, so just put the name of the folder here. (Not the path.)

#directory = "data_cw_linear_sample"
#directory = "data_cw_ellip_sample"
directory = "data_ellip_sin2_pulse_sample"


intensity_coef = np.load('./' + str(directory) + '/intensity_coef.npy')
params = np.load('./' + str(directory) + '/params.npy')
saddlepts = np.load('./' + str(directory) + '/saddle_pts.npy')

with open('./' + str(directory) + '/information', 'r') as f:
    for line in f:
        print(line, end='')

print("You are accessing the data found in the directory: " + str(directory)+"\nIf you would like to access another dataset change the directory variable in this program!!")
        
input("\nAny key to continue: ")


# In[ ]:

# To find information about a particular set of saddle points corresponding to a certain field mixing
# find the index in intensity_coef and then use the same index on the saddlepts array i.e.
# intensity_coef[1] <-> saddlepts[1]
# or use the automated finder below.

# Note that the data for a particular intensity ratio can be found

print("Select the intensity ratio you would like to investigate further... The options are:\n")
for i, v in enumerate(intensity_coef):
    print("Type '" + str(i) + "' to select the intensity ratio of", intensity_coef[i])
which_field = int(input())
print("\nI have set the variables current_params, curret_inten_coef, current_saddlepts to the values corresponding to")
print("the intensity ratio: ", intensity_coef[which_field])

current_params = params[which_field]
curret_inten_coef = intensity_coef[which_field]
current_saddlepts = saddlepts[which_field]

print("\nThose values are: \n", " Params: \n", current_params, "\n Intensity coefficients: \n",
      curret_inten_coef, "\n Saddle points: \n", current_saddlepts)

print("\nYou can find the data for this intensity ratio with the files:")
if which_field<9:
    print('./' + str(directory) + "/data_by_intensity_ratio/0"+str(which_field)+"_params")
    print('./' + str(directory) + "/data_by_intensity_ratio/0"+str(which_field)+"_intensity_coef")
    print('./' + str(directory) + "/data_by_intensity_ratio/0"+str(which_field)+"_saddle_pts")
else:
    print('./' + str(directory) + "/data_by_intensity_ratio/"+str(which_field)+"_params")
    print('./' + str(directory) + "/data_by_intensity_ratio/"+str(which_field)+"_intensity_coef")
    print('./' + str(directory) + "/data_by_intensity_ratio/"+str(which_field)+"_saddle_pts")


# In[ ]:



